% ---------------------------------------------
% SyncFilter
% input: signal (struct)
%        fields: sampleFreq, centerFreq, data 
% output: filterd signal (struct)
% Author: Johan, some parts autogenerated.
% ---------------------------------------------
function [Filter_signal] = syncFilter(signal)
raw_data = signal.data;
[m,~] = size(raw_data);

% ---------------------------------------------------------
% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 03-May-2018 08:27:04
% DOFILTER Filters input x and returns output y.
% persistent Hd;
% if isempty(Hd)
%     Fstop = 0.05;  % Stopband Frequency
%     Fpass = 0.1;   % Passband Frequency
%     Astop = 60;    % Stopband Attenuation (dB)
%     Apass = 0.5;   % Passband Ripple (dB)
% 
%     h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass);
%     Hd = design(h, 'equiripple', ...
%             'MinOrder', 'any', ...
%             'StopbandShape', 'flat');
%     set(Hd,'PersistentMemory',true);
% end
% ---------------------------------------------------------
    Fstop = 0.05;  % Stopband Frequency
    Fpass = 0.1;   % Passband Frequency
    Astop = 60;    % Stopband Attenuation (dB)
    Apass = 0.5;   % Passband Ripple (dB)

    Hdd = designfilt('highpassfir','PassbandFrequency',Fpass, ...
         'StopbandFrequency',Fstop,'PassbandRipple',Apass, ...
         'StopbandAttenuation',Astop,'DesignMethod','equiripple');
    fvtool(Hdd)
    for i=1:m
        Filter_signal(i,:) = filtfilt(Hdd,raw_data(i,:));
    end
end


